{% raw %}
name: CI/CD

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: actions/setup-python@cfd55ca82492758d853442341ad4d8010466803a
        with:
          python-version: '3.12'
      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@cfd55ca82492758d853442341ad4d8010466803a
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.cache/pip
          key: v1-${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            v1-${{ runner.os }}-python-${{ matrix.python-version }}-

      - name: Install Poetry
        run: pipx install poetry
        shell: bash

      - name: Install dependencies
        run: poetry install --with dev
        shell: bash

      - name: Run tests
        env:
          PGHOST: ${{ secrets.DB_POSTGRES_TEST_HOST}}
          PGPORT: ${{ secrets.DB_POSTGRES_TEST_PORT }}
          PGUSER: ${{ secrets.DB_POSTGRES_TEST_USERNAME}}
          PGPASSWORD: ${{ secrets.DB_POSTGRES_TEST_PASSWORD}}
          PGDATABASE: ${{ secrets.DB_POSTGRES_TEST_PATIENT_SYNTHETIC_DATA}}
        run: poetry run pytest --cov=src --cov-report=xml
        shell: bash

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          fail_ci_if_error: true
          verbose: true

  build-docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: Set up Python
        uses: actions/setup-python@cfd55ca82492758d853442341ad4d8010466803a
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.cache/pip
          key: v1-${{ runner.os }}-python-3.12-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            v1-${{ runner.os }}-python-3.12-

      - name: Install Poetry
        run: pipx install poetry
        shell: bash

      - name: Install dependencies
        run: poetry install --with dev
        shell: bash

      - name: Build documentation
        run: poetry run mkdocs build --strict
        shell: bash

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: Set up Python
        uses: actions/setup-python@cfd55ca82492758d853442341ad4d8010466803a
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
{% endraw %}
